### ISSUE TITLE
Image upload for exercise

### ISSUE THREAD

**Issue by wallysoncarvalho** [wallysoncarvalho/my-gym-coach#3]
## Task
Create an endpoint to upload images to local storage. In a future version we will upload it to AWS S3,

## Requirements
- [x] Store images on application properties new attribute `exercise.path`. It should read value from environment variable `EXERCISE_PATH` or fallback to a defaul.
- [x] Accept **only** images of formats `jpeg`and `png`
- [x] Maximum of 5 images per upload
- [x] Max size of each image is **1MB**
- [x] Each image should be **renamed** with a unique name that is defined by a UUID
- [x] The return should contain an array with the information of the created images. Each element of this array should be an object with the attributes: `name `and `uri`. The `name `attribute refers to the name of the image and `uri` is the endpoint to download the resource.
- [x] Create endpoint to download image stored on `EXERCISE_PATH` from resource `api/v1/exercises/images/<image-id>`
